Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,35 +1,67 @@
-name: Claim Daily Reward
-
+name: Humanity
 on:
   schedule:
     - cron: '0 1 * * *'
   workflow_dispatch:
 
 jobs:
-  claim:
+  start-bot:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v4
         with:
-          node-version: '16'
+          node-version: '18'
+
+      - name: Fetch GitHub User Info
+        run: |
+          GIT_NAME=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
+                         -H "Accept: application/vnd.github.v3+json" \
+                         https://api.github.com/user | jq -r '.login')
+
+          GIT_EMAIL=$(curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
+                          -H "Accept: application/vnd.github.v3+json" \
+                          https://api.github.com/user | jq -r '.email')
+
+          if [ -z "$GIT_EMAIL" ] || [ "$GIT_EMAIL" == "null" ]; then
+            GIT_EMAIL="${GIT_NAME}@users.noreply.github.com"
+          fi
+
+          echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
+          echo "GIT_EMAIL=$GIT_EMAIL" >> $GITHUB_ENV
+
+      - name: Fetch privateKeys.json
+        run: |
+          echo "🔄 Fetching privateKeys.json..."
+          curl -H "Authorization: token ${{ secrets.PRIVATE_SECRET }}" \
+               -H "Accept: application/vnd.github.v3" \
+               https://api.github.com/repos/${GIT_NAME}/private/contents/privateKeysHumanity.json \
+               | jq -r '.content' | base64 --decode > privateKeys.json
+
+          if ! jq empty privateKeysHumanity.json >/dev/null 2>&1; then
+            echo "⚠️ Invalid JSON detected! Replacing with an empty array."
+            echo "[]" > privateKeys.json
+          fi
 
       - name: Install Dependencies
         run: npm install
 
-      - name: Run Claim Script
+      - name: Run Script
         run: node claim.js
 
       - name: Commit and Push Updated Log
         run: |
-          git config --global user.name "0xvirly"
-          git config --global user.email "virlyairina@gmail.com"
-          git add log.txt
-          git commit -m "Update log.txt"
-          git push
+            git config --global user.name "$GIT_NAME"
+            git config --global user.email "$GIT_EMAIL"
+            git add log.txt
+            git commit -m "Update log.txt"
+            git push origin main
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Cleanup
+        run: rm -f privateKeys.json
